"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
version = 2
final_space = true
console_title_template = '{{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = "python"
    style = "plain"
    foreground = "white"
    background = "transparent"
    template = "{{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ end }} "
    [blocks.segments.properties]
      home_enabled = true

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    background = 'transparent'
    foreground = 'lightGreen'
    template = '{{ .Path }}'

    [blocks.segments.properties]
      style = 'full'

  # # this makes the prompt very slow
  # [[blocks.segments]]
  #   type = 'git'
  #   style = 'plain'
  #   foreground = 'p:grey'
  #   background = 'transparent'
  #   template = '  {{ .HEAD }}</>'

  #   [blocks.segments.properties]
  #     branch_icon = ''
  #     commit_icon = '@'
  #     fetch_status = true

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = 'yellow'
    background = 'transparent'
    template = '{{ .FormattedMs }}'

    [blocks.segments.properties]
      threshold = 5000

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    type = "time"
    style = "plain"
    foreground = "white"

    [blocks.segments.properties]
      time_format = "15:04:05"

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = [
      "{{if gt .Code 0}}red{{end}}",
      "{{if eq .Code 0}}cyan{{end}}",
    ]
    background = 'transparent'
    template = '➜ '

[transient_prompt]
  foreground_templates = [
    "{{if gt .Code 0}}red{{end}}",
    "{{if eq .Code 0}}cyan{{end}}",
  ]
  background = 'transparent'
  template = '➜ '

[secondary_prompt]
  foreground = 'magenta'
  background = 'transparent'
  template = '❯❯ '